---
- name: "services: Restarting `vsftpd` service"
  become: yes
  ansible.builtin.service:
    name: "{{ vsftpd_service }}"
    state: restarted

- name: "services: Restarting `rsyslog` service"
  become: yes
  ansible.builtin.service:
    name: "{{ rsyslog_service }}"
    state: restarted

- name: "services: Reloading OpenSSH Server service"
  become: yes
  ansible.builtin.service:
    name: "{{ sshd_service }}"
    state: reloaded
...
