---
- name: "accounts: Creating `{{ ftp_group['name'] }}` group"
  become: yes
  ansible.builtin.group:
    name: "{{ ftp_group['name'] }}"
    state: present
    gid: "{{ ftp_group['gid'] }}"

- name: "accounts: Creating `{{ ftp_user['name'] }}` account"
  become: yes
  ansible.builtin.user:
    comment: "vsftpd service account"
    name: "{{ ftp_user['name'] }}"
    uid: "{{ ftp_user['uid'] }}"
    group: "{{ ftp_group['name']}}"
    password_lock: yes
    shell: "/bin/bash"
    home: "{{ ftp_root }}"
    create_home: no

- name: "accounts: Creating groups for `ftp_users`"
  become: yes
  ansible.builtin.group:
    name: "{{ item['name'] }}"
    state: present
    gid: "{{ item['id'] }}"
  loop: "{{ ftp_users }}"

- name: "accounts: Creating regular accounts for `ftp_users`"
  become: yes
  ansible.builtin.user:
    name: "{{ item['name'] }}"
    uid: "{{ item['id'] }}"
    group: "{{ item['name']}}"
    groups: "{{ ftp_group['name']}}"
    password: "{{ item['password'] | password_hash('sha512') }}"
    shell: "/bin/sh"
    home: "{{ ftp_root }}/{{ item['name'] }}"
    comment: "umask=0007"
    create_home: no
  loop: "{{ ftp_users | selectattr('role','equalto','user') }}"

- name: "accounts: Creating admin accounts for `ftp_users`"
  become: yes
  ansible.builtin.user:
    name: "{{ item['name'] }}"
    uid: "{{ item['id'] }}"
    group: "{{ item['name']}}"
    groups: "{{ ftp_users | map(attribute='name') | join(',') }},{{ ftp_group['name'] }}"
    password: "{{ item['password'] | password_hash('sha512') }}"
    shell: "/bin/bash"
    home: "{{ ftp_root }}"
    comment: "umask=0007"
    create_home: no
  loop: "{{ ftp_users | selectattr('role','equalto','admin') }}"
...
