---
- name: "user: Creating `{{ ftp_group['name'] }}` group"
  become: yes
  ansible.builtin.group:
    name: "{{ ftp_group['name'] }}"
    state: present
    gid: "{{ ftp_group['gid'] }}"

- name: "user: Creating `{{ ftp_user['name'] }}` user"
  become: yes
  ansible.builtin.user:
    comment: "vsftpd maps virtual users to this one"
    name: "{{ ftp_user['name'] }}"
    uid: "{{ ftp_user['uid'] }}"
    group: "{{ ftp_group['name']}}"
    password_lock: yes
    shell: "/bin/bash"
    home: "{{ ftp_root }}"
    create_home: no
...
