---
- name: "packages: Installing packages on Debian systems"
  become: yes
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  when: (ansible_os_family | lower) == 'debian'
...
