---
- name: "Deploying FTP servers for B2B"
  hosts: test-1,test-2
  roles:
    - role: vsftpd
      ftp_users:
        - name: user1
          password: test1
          role: user
        - name: user2
          password: test2
          role: user
        - name: user3
          password: test3
          role: admin
      ftp_root: "/srv/ftproot"
      vsftpd_rsa_cert_file: "/etc/vsftpd.conf.d/cert.pem"
      vsftpd_rsa_cert: |
        -----CERTIFICATE CONTENT HERE----
