---
- name: "Deploying FTP servers for B2B"
  hosts: test-1,test-2
  roles:
    - role: vsftpd
      ftp_users:
        - name: user1
          id: 2001
          password: test1
          role: user
        - name: user2
          id: 2002
          password: test2
          role: user
        - name: user3
          id: 2003
          password: test3
          role: admin
        - name: user4
          id: 2004
          password: test4
          role: user
        - name: user5
          id: 2005
          password: test5
          role: admin
      ftp_root: "/srv/ftproot"
      vsftpd_rsa_cert_file: "/etc/vsftpd.conf.d/cert.pem"
      vsftpd_rsa_cert: |
        -----CERTIFICATE CONTENT HERE----
